<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-CJECPP6" failures="1" tests="1" name="Login Successful" time="13.64" errors="0" timestamp="2023-11-06T10:15:22 CET">
  <testcase classname="com.parabank.tests.WebsiteLoginSuccessfulTest" name="loginSuccessful" time="0.562">
    <failure type="java.lang.AssertionError" message="Cannot login into the account expected [Accounts Overview] but found [Error!]">
      <![CDATA[java.lang.AssertionError: Cannot login into the account expected [Accounts Overview] but found [Error!]
at com.parabank.tests.WebsiteLoginSuccessfulTest.loginSuccessful(WebsiteLoginSuccessfulTest.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- loginSuccessful -->
</testsuite> <!-- Login Successful -->
